# Needed as trusty (the default) doesn't support python 3.7.
# Remove once xenial is made default.
# https://github.com/travis-ci/travis-ci/issues/9815
dist: xenial

addons:
  apt:
    sources:
    - sourceline: 'deb https://downloads.skewed.de/apt/xenial xenial universe'
      key_url: 'https://pgp.skewed.de/pks/lookup?op=get&search=0x612DEFB798507F25'
    - sourceline: 'deb https://downloads.skewed.de/apt/trusty trusty universe'
      key_url: 'https://pgp.skewed.de/pks/lookup?op=get&search=0x612DEFB798507F25'
    - sourceline: 'deb-src https://downloads.skewed.de/apt/trusty trusty universe'
      key_url: 'https://pgp.skewed.de/pks/lookup?op=get&search=0x612DEFB798507F25'
    packages:
    - python-graph-tool
    - python3-graph-tool

language: python

python:
  - 3.5
  - 3.6
  - 3.7

matrix:
  include:
    - python: 2.7
      dist: trusty  # "cannot import name QtOpenGL" with xenial
      cache: pip  # avoid PySide wheel build

before_install:
  - echo $(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
  - mkdir -p $(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
  - if [[ $(python -c 'import sys; print(sys.version_info[0])') = 3 ]] ;
    then ln -s /usr/lib/python3/dist-packages/graph_tool $(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())");
    else ln -s /usr/lib/python2.7/dist-packages/graph_tool $(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"); fi

install:
  - pip install -U --upgrade-strategy eager .[alldeps,test,doc]
  # Update dependencies (e.g. numpy formatting changed in v1.14).

script:
# - make lint
  - make test
  - make doc

after_success:
  - coveralls