language: python
cache: pip  # cache wheels for faster tests (PySide build can timeout)
python:
  - 2.7
  - 3.5
  - 3.6
# Enable 3.7 without globally enabling sudo and xenial
# https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial

addons:
  apt:
    packages:
      - xvfb

install:
  - pip install -U --upgrade-strategy eager .[alldeps,test,doc]
  # Update dependencies (e.g. numpy formatting changed in v1.14).

script:
# - make lint
  - make test
  - make doc

after_success:
  - coveralls
