# Needed as trusty (the default) doesn't support python 3.7.
# Remove once xenial is made default.
# https://github.com/travis-ci/travis-ci/issues/9815
dist: xenial

language: python

python:
  - 3.5
  - 3.6
  - 3.7

matrix:
  include:
    - python: 2.7
      dist: trusty  # "cannot import name QtOpenGL" with xenial
      cache: pip  # avoid PySide wheel build

addons:
  apt:
    packages:
      - libqt5gui5  # pyqt5>5.11 otherwise cannot load the xcb platform plugin
      - libflann-dev

install:
  - pip install --upgrade --upgrade-strategy eager .[dev]
  # Upgrade to test with the latest version of our dependencies.

before_script:
  # As graph-tool cannot be installed by pip, link to the system installation
  # from the virtual environment.
  # TODO: remove the condition once we drop python 2.7.
  - if [[ $(python -c 'import sys; print(sys.version_info[0])') = 3 ]] ;
    then ln -s "/usr/lib/python3/dist-packages/graph_tool" $(python -c "import site; print(site.getsitepackages()[0])");
    else ln -s "/usr/lib/python2.7/dist-packages/graph_tool" $(python -c "import site; print(site.getsitepackages()[0])"); fi

script:
# - make lint
  - make test
  - make doc

after_success:
  - coveralls
