# Needed as trusty (the default) doesn't support python 3.7.
# Remove once xenial is made default.
# https://github.com/travis-ci/travis-ci/issues/9815
dist: xenial

language: python

python:
  - 3.5
  - 3.6
  - 3.7

matrix:
  include:
    - python: 2.7
      dist: trusty  # "cannot import name QtOpenGL" with xenial
      cache: pip  # avoid PySide wheel build

addons:
  apt:
    packages:
    - libqt5gui5  # pyqt5>5.11 fails to load the xcb platform plugin without it

install:
  - pip install --upgrade --upgrade-strategy eager .[dev]
  # Upgrade to test with the latest version of our dependencies.

script:
# - make lint
  - make test
  - make doc

after_success:
  - coveralls
